### ISSUE TITLE
sh: Syntax error: Bad fd number

### ISSUE THREAD

**Issue by guanyanliang** [farmercode/one_shell_install_lnmp#1]
sudo rm /bin/sh

sudo ln -s /bin/bash /bin/sh

After this again restart the installation.

**Comment by guanyanliang** [comment]
make -f objs/Makefile
make[1]: Entering directory '/one_shell_install_lnmp-master/nginx-1.8.0'
cd ../pcre-8.37/ \
&& if [ -f Makefile ]; then make distclean; fi \
&& CC="cc" CFLAGS="-O2 -fomit-frame-pointer -pipe " \
./configure --disable-shared  --enable-jit
/bin/sh: 第 0 行: cd: ../pcre-8.37/: 没有那个文件或目录
objs/Makefile:1141: recipe for target '../pcre-8.37//Makefile' failed
make[1]: **\* [../pcre-8.37//Makefile] Error 1
make[1]: Leaving directory '/one_shell_install_lnmp-master/nginx-1.8.0'
Makefile:8: recipe for target 'build' failed
make: **\* [build] Error 2

**Comment by guanyanliang** [comment]
ubuntu是php5.5.30

**Comment by farmercode** [comment]
你好，最近比较忙，所以没有怎么登陆git。你的问题我看到了，我去检查一下脚本啊！

**Comment by farmercode** [comment]
你好@guanyanliang，你反应的问题我确认了一下！确实存在，就把脚本又整理了一遍。你可以重新安装试试，我在自己的新的kylin ubuntu15.10里面安装成功了。如有问题请及时反馈！

**Comment by farmercode** [comment]
今天在看一本shell的书的时候看到，#!/bin/sh会调用你系统默认的shell解释器，而绝大多数linux上面的默认shell解释器是#!/bin/bash,而#!/bin/sh是很多商业Unix上面默认的shell解释器！
